version : "3.7"
services:  
  node:
    build: .
    init: true
    restart: always
    volumes:
    - ./config:/app/config
    - ./mp3:/app/mp3
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/gtoken.json